# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Papers
    identifier: Y7xE8GHJ
    url: /publications/
    weight: 10
  - name: News
    identifier: Ls8rDxWS
    url: /news/
    weight: 20  
  - name: Experience
    identifier: cvYrQHgF
    url: /experience/
    weight: 30
  - name: Awards
    identifier: HsSA-kTsw
    url: /awards/
    weight: 40
  - name: Teaching
    identifier: kIoA-SMud
    url: /teaching/
    weight: 50
  - name: Research
    identifier: research
    url: https://neubauer-group.github.io
    weight: 60